name: 'JacoDB analyzer'
description: 'JacoDB analyzer implementing IFDS algorithm'
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.args }}
inputs:
  args:
    description: Arguments for the analyzer
    required: false
    default: --help
