on:
  push:
  workflow_dispatch:

jobs:
  main_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run analyzer
        uses: ./
        with:
          args: --help

      # - name: Setup SSH session on failure
      #   uses: lhotari/action-upterm@v1
      #   if: ${{ failure() }}
      #   with:
      #     wait-timeout-minutes: 5
